name: TestAction
on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: victor.com
    needs: [build]  
    steps:
      - name: Run a one-line script
        run: echo Deploy DEV!
        
  deploy-hom:
    runs-on: ubuntu-latest
    environment: 
      name: hom
      url: victor.com
    needs: [deploy-dev]  
    steps:
      - name: Run a one-line script
        run: echo Deploy HOM! 
        
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: victor.com
    needs: [deploy-hom]  
    steps:
      - name: Run a one-line script
        run: echo Deploy PROD!    
                
